### ISSUE TITLE
sequence with all Ns gets a lineage assignment of A.1 with bootstrap 63

### ISSUE THREAD

**Issue by rainwala** [hCoV-2019/pangolin#22]
Hi, I thought I'd share that with you: I had a failed sequence that had all Ns (100% in the non-UTR regions), and pangolin outputted A.1 with bootstrap 63. Is this expected behaviour?

**Comment by rambaut** [comment]
We are aware of this issue and looking into it.

**Comment by aineniamh** [comment]
I have now implemented a check in pangolin that exits if your input fasta file has >50% N content because it's likely that will produce inaccurate results. 
Also, now in addition to the `-bb` ultrafast bootstrapping we had been running til now, pangolin is now running a likelihood test  (iqtree's `-alrt` flag and outputting that as a result column too to provide further information about the placement in the tree by iqtree. It's *also* now running the iqtree `-au` flag and rejecting trees that don't meet the p-value threshold. Some information about these new criteria can be found [here](http://www.iqtree.org/doc/Command-Reference).
