### ISSUE TITLE
Some entries in the lineages.csv bootstrap column look like dates

### ISSUE THREAD

**Issue by joshsinger** [hCoV-2019/pangolin#23]
e.g. Apr-99

Maybe this got auto-converted from 04/99 e.g. in Excel?

Also, is it documented anywhere how to interpret this column?

**Comment by aineniamh** [comment]
The output has been updated and now will output regular-looking (i.e. single integer) UF-bootstrap and SH-alrt values. The original format was due to iqtree preserving the bootstraps that existed in the guide tree. I'm now just parsing those out and only outputting the relevent values.  I'm also hoping that in future Excel won't come anywhere near the csv, so shouldn't happen again!
