### ISSUE TITLE
Lineage B.11 in lineages.csv has no representatives.

### ISSUE THREAD

**Issue by joshsinger** [hCoV-2019/pangolin#25]
$ `grep "B\.11" lineages.csv 
Netherlands/NoordBrabant_28/2020|EPI_ISL_414537||Netherlands|Noord_Brabant||2020-03-08,B.11,90/96,0.01,
Netherlands/NoordBrabant_30/2020|EPI_ISL_414539||Netherlands|Noord_Brabant||2020-03-08,B.11,Apr-92,0.01,
Netherlands/NoordBrabant_31/2020|EPI_ISL_414540||Netherlands|Noord_Brabant||2020-03-08,B.11,90/95,2.15,
Netherlands/NoordBrabant_32/2020|EPI_ISL_414541||Netherlands|Noord_Brabant||2020-03-08,B.11,90/99,0.64,
Netherlands/NoordBrabant_35/2020|EPI_ISL_414544||Netherlands|Noord_Brabant||2020-03-09,B.11,90/98,0.01,
Netherlands/Utrecht_14/2020|EPI_ISL_414553||Netherlands|Utrecht||2020-03-09,B.11,98,1.3,`

**Comment by joshsinger** [comment]
I checked the file, there are no other lineages that do not have representatives.

**Comment by aineniamh** [comment]
Hi Josh, 
We've redone the lineages as of that release (lineages.csv will now be stored on hCov-2019/lineages repository). With more data coming in, we're having to re-evaluate the lineages manually. It was revealed that B.11 is actually just part of B.7, which is why the representative sequences were taken out. The most recent alignment and guide tree reflect that. As of 2020-04-27, there's an updated guide tree and alignment and I'll add the corresponding csv to the lineages repository today. Thanks for pointing it out though!

**Comment by joshsinger** [comment]
This is great. I'll continue to provide feedback on the lineage table in the other github repo.
