### ISSUE TITLE
Awesome package, do you think you could put it on pypi?

### ISSUE THREAD

**Issue by theboocock** [hCoV-2019/pangolin#46]
Hey great work on this package. I wondered whether you could put it on pypi I was hoping to include it in a conda environment for a pipeline I have been working on. 

Thanks again for your great work!

**Comment by aineniamh** [comment]
Thanks! I'm holding off putting it on pypi at the moment because pangolin still being updated **very** regularly. If you want to add it to a conda recipe (you probably already know this) you can add it into the yaml (or whatever) file by adding this: 
```
  - pip:
    - git+https://github.com/hCoV-2019/lineages.git
    - git+https://github.com/hCoV-2019/pangolin.git
```
in addition to the other dependencies in the [environment](https://github.com/hCoV-2019/pangolin/blob/master/environment.yml) file. Hopefully that helps as a short-term solution and more medium term I will add it to pypi.

**Comment by sidneymbell** [comment]
Hi @aineniamh! Would you feel comfortable putting pangolin on pypi now that things have settled a bit? Would be super helpful for adding it into workflows / as a dependency for other work. Thanks!
