### ISSUE TITLE
/tmp and .snakemake clash when running two at once

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#51]
Need to use `tmpdir()` (`import tempfile`?) for each run - do not put directly into $TMPDIR
https://docs.python.org/3/library/tempfile.html
Otherwise I can't run > 1 easily when using `-o folder/folder2` etc

Also can you put the `.snakemake` folder in the isolated temp dir too?

**Comment by aineniamh** [comment]
I've added the ``.snakemake`` folder to the temp dir now too. :) 

So I have been using the ``tempfile`` module since your last issue about this, but am invoking it using ``tempfile.gettempdir()`` and then writing to that, which is how it was described in the docs [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir). This is why by default it's writing to the $TMPDIR if no other tempdir is specified with ``--tempdir``.

You can also overwrite the default temp option with ``--tempdir`` and write temp files wherever you like, and I've made that a ``tempfile.tempdir`` thing now too. I still have snakemake handling the removal of the temporary files.

You can run more than 1 instance as there's unique hashing of the tax names and snakemake is being run in ``--nolock`` mode, so it **shouldn't** be an issue to run more than one instance and have it being written to the same directory.

**Comment by aineniamh** [comment]
I'm going to close this but open it again if what I did wasn't what you meant.

**Comment by tseemann** [comment]
I agree I was not very clear.
You are definetly honouring $TMPDIR
But there needs to be an extra unique folder _within_ that _per_ pangolin run.
If i run two pangolins at once they over-write each others files otherwise?

**Comment by tseemann** [comment]
@aineniamh thanks for reopening. I'm noticing the `.snakemake` folder is still being created in the folder I launch pangolin from, so if i launch two from the same $PWD distaster ensues.

**Comment by aineniamh** [comment]
No worries. I've implemented your suggested tempdir now `tempfile.TemporaryDirectory(suffix=None, prefix=None, dir=None)`, and just pushed it to v1.1.3. Haven't done a release yet, but will look into the `.snakemake` thing now, thought I'd fixed it with` --shadow-prefix`, but I now realise that was something else. I'll have a read around and see how to redirect it.

**Comment by aineniamh** [comment]
So I **think** I've solved this now. I couldn't find any option to redirect where snakemake wrote the `.snakemake` directory. So instead, I've changed the working directory for where snakemake is being executed to the tempdir and that is now working on my system to write the `.snakemake` stuff to the temp directory.
