### ISSUE TITLE
Error in rule assign_lineages:

### ISSUE THREAD

**Issue by swantan** [hCoV-2019/pangolin#55]
Hi, thank you for your wonderful work and documentation! I had been able to follow through. However, I was not able to run my file and I got this error message. I would also like to know is this only support/analyze GISAID sequences and not sequences from NCBI?

Thanks and I appreciate your help.

```
Error in rule assign_lineages:
    jobid: 0
    output: /Users/Swan/Documents/_ResearchProjects/15. Covid-19/lineage_report.csv

RuleException:
CalledProcessError in line 87 of /Users/Swan/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_file.smk:
Command 'set -euo pipefail;  touch /Users/Swan/Documents/_ResearchProjects/15. Covid-19/lineage_report.csv' returned non-zero exit status 1.
  File "/Users/Swan/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin/scripts/assign_query_file.smk", line 87, in __rule_assign_lineages
  File "/Users/Swan/miniconda3/envs/pangolin/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
```

**Comment by aineniamh** [comment]
I see where the issue lies, it's trying to create a file in a directory called `/Users/Swan/Documents/_ResearchProjects/15. Covid-19` and failing. If you double check that that path exists on your machine, that is likely to be the issue. 

If that's not where the problem lies, I actually changed that part of the code for other reasons yesterday. If you run ``git pull`` and then ``python setup.py install``, this may have resolved itself. Let me know how you get on!

**Comment by aineniamh** [comment]
@swantan just checking if you've followed up with this issue. We have a new release as of a few minutes ago [here](https://github.com/hCoV-2019/pangolin/releases/tag/v1.1.5) if you want to try and see whether your issue has been resolved? We support SARS-COV2 sequence with a minimum sequence length of 10,000 bp and maximum N content of 0.5.

**Comment by swantan** [comment]
Hi Aine, thanks for getting back to me. So the issue wasn't the first one, as I did successfully run one file (let say file A) earlier. So I went ahead and just updated my repository. And now,  it (the previously failed - file B) did run, however, the report I got was showing 'fail' status for every sequences. [Note: there are almost the same files, but with edited header in file B] so, I am not sure if different style of header cause the issue.

**Comment by aineniamh** [comment]
So the header is hashed out in the analysis and will not make any difference to pangolin. We do have the sequence length and N content filters in order for the analysis to be run without just failing. 

For me to help, can you post up the output file here and the exact command you're running. Extra help would be the sequence file, but that's okay if you can't share that. Minimally, I will need some more detailed information about what was run and how in order to help. 

Also, as of a few minutes ago, we are now on release v1.1.6, if you run `python setup.py install` again and check `pangolin -v` to make sure you're running the most up-to-date release!

**Comment by swantan** [comment]
Thank you for your great help. I think I figured out now the issue so it's the sequence length and you mentioned earlier it needs to be a minimum sequence length of 10,000bp. 

File A I got full-length sequences but file B is just spike protein region. However, I still attached the both the report here for your reference.

[lineage_report_A.xlsx](https://github.com/hCoV-2019/pangolin/files/4577983/lineage_report_A.xlsx)
[lineage_report_B.xlsx](https://github.com/hCoV-2019/pangolin/files/4577984/lineage_report_B.xlsx)

**Comment by aineniamh** [comment]
Ah yes that'll be the reason, by default `pangolin` won't attempt to run unless you've a genome length > 10,000bp. It is possible to change this when you run `pangolin` as follows: 
```
pangolin <query_file> --min-length 3000
```
But I would reccommend being cautious in interpreting the output as some key "lineage defining" snps almost certainly are present outside of the spike region you've sequenced and the result you get will not be informed by the full genome. With that in mind, I'm glad you've got `pangolin` working and appreciate the feedback!
