### ISSUE TITLE
Is lineage_report.csv the only output?

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/pangolin#64]
Was wondering if you would consider `--outfile [lineage_report.csv]` instead of a whole folder?

And also allow `--outfile -` which means to `stdout` ?

Or maybe add a `outdir/pangolin.log` file for debugging?

So `pangolin file.fasta > report.csv` would work basically.

**Comment by aineniamh** [comment]
When you run with the flag `--panGUIlin` you get a second output file that gives you some background info on the lineages that are in your query file.  

But I've pushed a commit that allows `--outfile <your_fave_outfile_name> ` as an optional argument so you can change the name of `lineage_report.csv` (relative paths will work and it's compatible with/without `--outdir`).  

The `--outfile -` request is trickier because `pangolin` is built on snakemake and that relies on target file names being specified and it also prints a lot of ~~crap to~~ information to stdout as well as stderr. I played around with it a bit today but got as far as `snakemake` creating a file called `-` 🤦‍♀️ . 

I'll work on integrating `--log` over the next day or two. 👍

**Comment by tseemann** [comment]
The GUI is something i haven't looked into yet.

_"relative paths will work and it's compatible with/without --outdir"_
those are the magic words, thank you!

Yep, stdout is often tricky and I accept your rebuttal :-)
