### ISSUE TITLE
Mismatch reference name between lineage data and pangolin

### ISSUE THREAD

**Issue by biocyberman** [hCoV-2019/pangolin#67]
As I understand, reference name of the current release of `lineages` is "outgroup_A". But this line expects "Wuhan..." :

https://github.com/hCoV-2019/pangolin/blob/ca5e359d066b1f114785db274c76ea0615f4fc13/pangolin/scripts/all_snps.py#L92

So lineage should update or this line should be changed.

**Comment by aineniamh** [comment]
This script is part of the `prepare_package_data` pipeline, not run routinely as part of pangolin. It is run as part of the process to create the data files that exist on` lineages`, so the default outgroup value is correct as this is the name of the outgroup we use.

I am in the process of developing the `prepare_package_data` pipeline for use beyond just me, so that custom lineages can be supplied to `pangolin` but the documentation is not quite there yet.

**Comment by biocyberman** [comment]
Thanks for the explanation. In any case, I would suggest then to use reference header something like this `>reference Wuhan/WH04/2020`. This make it unmistakably obvious that it is reference and which one it is.
