### ISSUE TITLE
Difference reference to nextstrain?

### ISSUE THREAD

**Issue by biocyberman** [hCoV-2019/pangolin#72]
Hi 
Sorry to have many questions, but I need to verify all important details. 
[Ncov](https://github.com/nextstrain/ncov/blob/master/config/reference.gb) repo is using a difference refernce than `pangolin` (Wuhan/WH04/2020. Could you @aineniamh  or someone in the team give the reason to do this? Would it be a good idea to use the same reference sequence between the two?

**Comment by aineniamh** [comment]
Yes of course no worries. 

`pangolin` uses Wuhan/WH04/2020 as the outgroup in the guide tree and also as the reference upon which to template SNP assignment. Because of its associated metadata, it is a logical sequence to use as an outgroup for this outbreak. 

Because lineage B is nested within A, it also seemed logical to use an early A lineage sequence as the reference to template hierarcical SNP accumulation onto as it is more likely to reflect the order of mutation events that occured during the course of the outbreak. 

I can't speak for the reasons the developers in next strain chose Wuhan-Hu-1, but it is the reference sequence in Genbank so is also a logical sequence to pick.

**Comment by biocyberman** [comment]
Great. Really appreciate your prompt response. FWIW, I can't find `Wuhan/WH04/2020` in genbank. Need a genbank file to run with `augur` to check. It will be great if you could share that. I am waiting to have access to next GISAID and download the sequence myself.  

Alternatively, I saw somewhere either in `pangolin` or in `lineages` repo mentioned that it is possible to add more sequences to the default data. Is this removed or I remember incorrectly?

**Comment by biocyberman** [comment]
Ok found it here: https://github.com/hCoV-2019/pangolin/blob/master/docs/update_guide_tree.md But the first question about `Wuhan/WH04/2020` genbank file still valid.

**Comment by aineniamh** [comment]
I'm not sure if the WH04 reference is on genbank, I think just GISAID, so I can't share a genbank file with you. 

You can create your own setup, but I will create some more detailed documentation on how to actually do that and what is required.

**Comment by biocyberman** [comment]
Didn't fully realize that GISAID has 'private' sequences which are not uploaded to genbank. Thank you for helpful answers, as always. Got my account activated on GISAID.

**Comment by biocyberman** [comment]
> I'm not sure if the WH04 reference is on genbank, I think just GISAID, so I can't share a genbank file with you.
> 
> You can create your own setup, but I will create some more detailed documentation on how to actually do that and what is required.

@aineniamh  Could you share the GFF or BED file of the sequence? I got the sequence from GISAID but it is only in FASTA format. I can annotate the genome manually but will be much better to you the same annotation you have.

**Comment by rambaut** [comment]
WH04 is exactly the same length as the genbank reference sequence (Wuhan-Hu-1) and has only 2 SNP differences. You can use Wuhan-Hu-1 to annotate WH04 precisely.
